# Generated by Django 2.1.1 on 2020-12-01 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FAFA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setlocation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FAFA.User', unique=True),
        ),
    ]
