# Generated by Django 2.1.1 on 2020-12-01 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAFA', '0003_auto_20201202_0138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setlocation',
            old_name='user',
            new_name='user_id',
        ),
    ]
