# Generated by Django 2.1.1 on 2020-12-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAFA', '0006_auto_20201203_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='onCompanyRoad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='onHomeRoad',
            field=models.IntegerField(null=True),
        ),
    ]
