# Generated by Django 2.1.1 on 2020-12-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAFA', '0007_auto_20201208_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='onCompanyRoad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='onHomeRoad',
            field=models.IntegerField(default=0),
        ),
    ]
