# Generated by Django 2.1.1 on 2020-11-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAFA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10)),
                ('homeX', models.FloatField()),
                ('homxY', models.FloatField()),
                ('companyX', models.FloatField()),
                ('companyY', models.FloatField()),
            ],
        ),
    ]
