# Generated by Django 2.1.1 on 2020-11-30 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAFA', '0002_setlocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setlocation',
            old_name='companyX',
            new_name='company_X',
        ),
        migrations.RenameField(
            model_name='setlocation',
            old_name='companyY',
            new_name='company_Y',
        ),
    ]
