# Generated by Django 2.1.1 on 2020-11-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAFA', '0004_auto_20201130_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
    ]
